# Generated by Django 3.2 on 2021-04-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
