# Generated by Django 3.2 on 2021-04-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_rename_title_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.station'),
        ),
    ]
