# Generated by Django 3.2 on 2021-04-26 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_parameter_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
