# Generated by Django 3.2 on 2021-04-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_station_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='reading',
        ),
        migrations.AddField(
            model_name='parameter',
            name='readings',
            field=models.TextField(default=''),
        ),
    ]
