# Generated by Django 3.2 on 2021-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_parameter_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(default='-8.093178907962578,-34.88296508789063', max_length=200),
        ),
    ]
