# Generated by Django 3.2 on 2021-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
