# Generated by Django 3.2 on 2021-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='location',
            field=models.CharField(default='-8.093178907962578,-34.88296508789063', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
